config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :curriculums
  resources :courses
  resources :sections
  resources :sub_sections
  root 'curriculums#index'

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
    has_many :courses
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "dhh", password: (Rails.application.secrets.basic_auth), except: [:index, :show]
  # GET /curriculums
  # GET /curriculums.json
  def index
    @curriculums = Curriculum.all
  end

  # GET /curriculums/1
  # GET /curriculums/1.json
  def show
  end

  # GET /curriculums/new
  def new
    @curriculum = Curriculum.new
  end

  # GET /curriculums/1/edit
  def edit
  end

  # POST /curriculums
  # POST /curriculums.json
  def create
    @curriculum = Curriculum.new(curriculum_params)

    respond_to do |format|
      if @curriculum.save
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully created.' }
        format.json { render :show, status: :created, location: @curriculum }
      else
        format.html { render :new }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculums/1
  # PATCH/PUT /curriculums/1.json
  def update
    respond_to do |format|
      if @curriculum.update(curriculum_params)
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully updated.' }
        format.json { render :show, status: :ok, location: @curriculum }
      else
        format.html { render :edit }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculums/1
  # DELETE /curriculums/1.json
  def destroy
    @curriculum.destroy
    respond_to do |format|
      format.html { redirect_to curriculums_url, notice: 'Curriculum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculum_params
      params.require(:curriculum).permit(:time_estimate, :time_completed, :complete, :title)
    end
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/_form.html.erb
<%= form_for(@curriculum) do |f| %>
  <% if @curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
      <% @curriculum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_estimate %><br>
    <%= f.number_field :time_estimate %>
  </div>
  <div class="field">
    <%= f.label :time_completed %><br>
    <%= f.number_field :time_completed %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/curriculums/edit.html.erb
<h1>Editing Curriculum</h1>

<%= render 'form' %>

<%= link_to 'Show', @curriculum %> |
<%= link_to 'Back', curriculums_path %>

app/views/curriculums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Curriculums</h1>

<table>
  <thead>
    <tr>
      <th>Time estimate</th>
      <th>Time completed</th>
      <th>Complete</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculums.each do |curriculum| %>
      <tr>
        <td><%= curriculum.time_estimate %></td>
        <td><%= curriculum.time_completed %></td>
        <td><%= curriculum.complete %></td>
        <td><%= curriculum.title %></td>
        <td><%= link_to 'Show', curriculum %></td>
        <td><%= link_to 'Edit', edit_curriculum_path(curriculum) %></td>
        <td><%= link_to 'Destroy', curriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculum', new_curriculum_path %>

app/views/curriculums/new.html.erb
<h1>New Curriculum</h1>

<%= render 'form' %>

<%= link_to 'Back', curriculums_path %>

app/views/curriculums/show.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Demo Expandable list</title>
        <link rel="stylesheet" href="css/style.css" type="text/css" media="screen, projection">
        <script type="text/javascript" src="js/jquery-1.4.2.min.js">
        </script>
        <script type="text/javascript" src="js/scripts.js">
        </script>
        </script>
    </head>
    <body>
        <h1><b><%= @curriculum.title %></b></h1>
        <div id="listContainer">
            <div class="listControl">
                <a id="expandList">Expand All</a>
                <a id="collapseList">Collapse All</a>
            </div>
            <ul id="expList">
                
            <% @curriculum.courses.each do |course| %>
              <li><h3><%= link_to "#{course.title}", course %>(<%= course.time_estimate %>)</h3>
                    <ul>
                            <% course.sections.each do |section| %>
                             <li><%= link_to "#{section.title}", section %>(<%= section.time_estimate %>)</li>
                        <% end %>
                    </ul>
                      <%end %>
          
                    
              </li>

            </ul>
        </div>
    </body>
</html>





<p id="notice"><%= notice %></p>








<%= link_to 'Edit', edit_curriculum_path(@curriculum) %> |
<%= link_to 'Back', curriculums_path %>