config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :curriculums
  resources :courses
  resources :sections
  resources :sub_sections
  root 'curriculums#index'

end

app/models/sub_section.rb
class SubSection < ActiveRecord::Base
    belongs_to :section
end

app/controllers/sub_sections_controller.rb
class SubSectionsController < ApplicationController
  before_action :set_sub_section, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "dhh", password: (Rails.application.secrets.basic_auth), except: [:index, :show]

  # GET /sub_sections
  # GET /sub_sections.json
  def index
    @sub_sections = SubSection.all
  end

  # GET /sub_sections/1
  # GET /sub_sections/1.json
  def show
  end

  # GET /sub_sections/new
  def new
    @sub_section = SubSection.new
  end

  # GET /sub_sections/1/edit
  def edit
  end

  # POST /sub_sections
  # POST /sub_sections.json
  def create
    @sub_section = SubSection.new(sub_section_params)

    respond_to do |format|
      if @sub_section.save
        format.html { redirect_to @sub_section, notice: 'Sub section was successfully created.' }
        format.json { render :show, status: :created, location: @sub_section }
      else
        format.html { render :new }
        format.json { render json: @sub_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_sections/1
  # PATCH/PUT /sub_sections/1.json
  def update
    respond_to do |format|
      if @sub_section.update(sub_section_params)
        format.html { redirect_to @sub_section, notice: 'Sub section was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_section }
      else
        format.html { render :edit }
        format.json { render json: @sub_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_sections/1
  # DELETE /sub_sections/1.json
  def destroy
    @sub_section.destroy
    respond_to do |format|
      format.html { redirect_to sub_sections_url, notice: 'Sub section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_section
      @sub_section = SubSection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_section_params
      params.require(:sub_section).permit(:time_estimate, :time_completed, :complete, :title, :section_id)
    end
end

app/helpers/sub_sections_helper.rb
module SubSectionsHelper
end

app/views/sub_sections/_form.html.erb
<%= form_for(@sub_section) do |f| %>
  <% if @sub_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_section.errors.count, "error") %> prohibited this sub_section from being saved:</h2>

      <ul>
      <% @sub_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_estimate %><br>
    <%= f.number_field :time_estimate %>
  </div>
  <div class="field">
    <%= f.label :time_completed %><br>
    <%= f.number_field :time_completed %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.number_field :section_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_sections/edit.html.erb
<h1>Editing Sub Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_section %> |
<%= link_to 'Back', sub_sections_path %>

app/views/sub_sections/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/sub_sections/new.html.erb
<h1>New Sub Section</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_sections_path %>

app/views/sub_sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time estimate:</strong>
  <%= @sub_section.time_estimate %>
</p>

<p>
  <strong>Time completed:</strong>
  <%= @sub_section.time_completed %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @sub_section.complete %>
</p>

<p>
  <strong>Title:</strong>
  <%= @sub_section.title %>
</p>



<%= link_to 'Edit', edit_sub_section_path(@sub_section) %> |
<%= link_to 'Back', sub_sections_path %>