config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :curriculums
  resources :courses
  resources :sections
  resources :sub_sections
  root 'curriculums#index'

end

app/models/section.rb
class Section < ActiveRecord::Base
    belongs_to :course
    has_many :sub_sections
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, :set_course, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "dhh", password: (Rails.application.secrets.basic_auth), except: [:index, :show]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        @course.update_attribute(:time_estimate, @course.sections.map {|f| f.time_estimate}.compact.reduce(:+))
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end
    
    def set_course
      @course = @section.course
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:time_estimate, :time_completed, :complete, :title, :course_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_estimate %><br>
    <%= f.number_field :time_estimate %>
  </div>
  <div class="field">
    <%= f.label :time_completed %><br>
    <%= f.number_field :time_completed %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.number_field :course %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sections</h1>

<table>
  <thead>
    <tr>
      <th>Time estimate</th>
      <th>Time completed</th>
      <th>Complete</th>
      <th>Title</th>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.time_estimate %></td>
        <td><%= section.time_completed %></td>
        <td><%= section.complete %></td>
        <td><%= section.title %></td>
        <td><%= section.class %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time estimate:</strong>
  <%= @section.time_estimate %>
</p>

<p>
  <strong>Time completed:</strong>
  <%= @section.time_completed %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @section.complete %>
</p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>


<p>
  <strong>sub_sections:        Time Estimate(minutes)</strong>
  <% @section.sub_sections.each do |f| %>
  <p><%= f.title%>  <%= f.time_estimate %></p>
  <% end %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>